version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: database_name
      MARIADB_USER: database_user
      MARIADB_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    build:
      context: ./docker/db
      dockerfile: Dockerfile

  node-service:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USERNAME: database_user
      DB_PASSWORD: user_password
      DB_DATABASE: database_name

    depends_on:
      - db
    deploy:
      replicas: 3

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - node-service

volumes:
  db_data:
